### ISSUE TITLE
增加配置批量导入导出，支持占位符配置，解决ip等配置值的重复配置

### ISSUE THREAD

**Issue by carlsonsoft** [dotnetcore/AgileConfig#109]
问题描述:
当对不同项目进行部署时，每个项目的网络环境不同，每次部署新的项目，需要对多个项目的配置中的ip进行修改，效率较低

解决建议：
增加配置批量导入导出，引入占位符，和占位符变量配置，仅需从本地批量导出所需项目的配置，导入到项目的生产环境中，然后对占位符变量进行修改即可

**Comment by kklldog** [comment]
e...没懂，能不能举个栗子。。。。

**Comment by wlclass** [comment]
我猜是个多级继承的需求

**Comment by bc4250** [comment]
我猜 他的意思是 Dev Test Stage Prd等不同环境的配置key相同，内容也类似， 例如配置了些URL， 但是想在不同环境仅修改一下url中的host或ip部分就可以，而不用全部修改， 想引入环境变量， 这样共同的配置就是template， 变动的部分就是变量；

楼上提到的多级继承，如果能够在编辑画面预览到继承的内容并且知道是继承的那就最好了，目前没有.

个人觉得这个需求不是那么强烈， 再加环境变量就是配置系统的配置了， 哈哈哈.
Docker部署为例，个人建议如果变动部分不多的话，可以考虑用环境变量, 用agileconfig反而增加复杂度呢

**Comment by kklldog** [comment]
> 我猜 他的意思是 Dev Test Stage Prd等不同环境的配置key相同，内容也类似， 例如配置了些URL， 但是想在不同环境仅修改一下url中的host或ip部分就可以，而不用全部修改， 想引入环境变量， 这样共同的配置就是template， 变动的部分就是变量；
> 
> 楼上提到的多级继承，如果能够在编辑画面预览到继承的内容并且知道是继承的那就最好了，目前没有.
> 
> 个人觉得这个需求不是那么强烈， 再加环境变量就是配置系统的配置了， 哈哈哈. Docker部署为例，个人建议如果变动部分不多的话，可以考虑用环境变量, 用agileconfig反而增加复杂度呢

那导出来json，在编辑器里替换一下不是也很快嘛，哈哈。。。
