### ISSUE TITLE
[性能]应限制agc_config.v和agc_config_published.v的长度

### ISSUE THREAD

**Issue by saber-wang** [dotnetcore/AgileConfig#113]
当前没有限制长度，在Oracle中会生成NCLOB类型的字段，查询速度非常的慢

**Comment by kklldog** [comment]
oracle 的 varchar 最长多少？

**Comment by saber-wang** [comment]
@kklldog  varchar(4000) nvarchar(2000)

**Comment by kklldog** [comment]
> @kklldog varchar(4000) nvarchar(2000)

是么，我本来就是标记的 varchar4000 ，但是貌似Oracle不支持，所以我就特地把 Oracle 标记成了 clob 。。。https://github.com/dotnetcore/AgileConfig/blob/master/AgileConfig.Server.Data.Freesql/FluentApi.cs

**Comment by saber-wang** [comment]
@kklldog  应该是生成了nvarchar其他限制了长度的都是nvarchar。
nvarchar是2000

**Comment by kklldog** [comment]
> @kklldog 应该是生成了nvarchar其他限制了长度的都是nvarchar。 nvarchar是2000

这个倒问题不大，你可以手动再数据库把类型改成nvarchar也无妨

**Comment by saber-wang** [comment]
目前是这样处理的，但是这个要部署到很多的私有环境，一个个改也很麻烦

**Comment by kklldog** [comment]
> 目前是这样处理的，但是这个要部署到很多的私有环境，一个个改也很麻烦
Oracle 的问题真麻烦，我查了下有人说 utf16的时候只能2000，utf8的时候4000 ....

**Comment by kklldog** [comment]
https://blog.csdn.net/Hehuyi_In/article/details/108530885
