### ISSUE TITLE
前端应可选自动刷新

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/AgileConfig#116]
如上，在web界面，建议配置自动刷新选项，按5s 10 15 30 1min等刷新

**Comment by kklldog** [comment]
在管理界面上定时刷新？没get到点，这个配置还会被哪里修改呢？99%应该就是在管理界面上修改吧。1% api 修改，但是这种修改对于配置来说也不应该是一个频繁的动作。感觉没啥必要。

**Comment by yangbocheng** [comment]
比如首页区的ui数据，比如节点，应用，客户端，服务的数据

当有客户端的上下线，每次还要自己F5刷新才能看到，就不方便
我今天就遇到节点界面启动时出现了8个节点，而实际上是用docker-compose启动的3个节点，过了一会儿界面上一直显示8个节点全部在线。我还在想出了什么bug，结果刷新后，才逐渐变成了3个在线节点。

我觉得 首页，节点，应用，客户端，服务 的前端界面如果能加个刷新组件就好了。就和rabbitmq-admin界面的刷新组件一样，
![image](https://user-images.githubusercontent.com/32633109/211468559-e0ca2e70-74ac-42b0-a391-4d7dafbbad57.png)

**Comment by kklldog** [comment]
> 比如首页区的ui数据，比如节点，应用，客户端，服务的数据
> 
> 当有客户端的上下线，每次还要自己F5刷新才能看到，就不方便 我今天就遇到节点界面启动时出现了8个节点，而实际上是用docker-compose启动的3个节点，过了一会儿界面上一直显示8个节点全部在线。我还在想出了什么bug，结果刷新后，才逐渐变成了3个在线节点。
> 
> 我觉得 首页，节点，应用，客户端，服务 的前端界面如果能加个刷新组件就好了。就和rabbitmq-admin界面的刷新组件一样， ![image](https://user-images.githubusercontent.com/32633109/211468559-e0ca2e70-74ac-42b0-a391-4d7dafbbad57.png)

我记得首页的是概览信息是会定时刷新的，你f12看一下网络请求，好像是5s会拉一次。
