### ISSUE TITLE
webrequest的问题

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/AgileConfig#117]
项目中多处使用到了webrequest
我之前看到资料说webrequest底层现在自动使用了Httpclient, 因此是否可能使用httpclient后资源无法及时释放的问题。这点我也不确定。
是否考虑用现成的比如restsharp库

![image](https://user-images.githubusercontent.com/32633109/211480659-a5e3ceaf-ebeb-48d7-9cf3-ba200d16d6b6.png)

**Comment by kklldog** [comment]
确实，微软已经不推荐直接使用 httpwebrequest 这个类了，推荐使用 httpclient 来代替。有空我会改一下使用 IHttpClientFactory 来实现。
有个有趣的事：
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1146
在最新的 .net 源码上这部分的代码已经改进了，貌似在使用 cache 来避免大量创建 httpclient ，不会后面的版本 HttpWebRequest 又能用了吧，哈哈。

**Comment by yangbocheng** [comment]
微软反复横跳，哈哈

**Comment by kklldog** [comment]
Already use HttpClientFactory /HttpClient instead of HttpWebRequest
