### ISSUE TITLE
不支持Msql8.0环境自动生成表，以及无法正常使用

### ISSUE THREAD

**Issue by youweimao** [dotnetcore/AgileConfig#121]
mysql版本：8.0.32

直接配置连接，启动：The given key '20306' was not present in the dictionary 错误

连接字符串添加 chartset=utf8 

报：The given key '0' was not present in the dictionary  错误

通过其他方式把表导入mysql，功能无法正常使用
![image](https://user-images.githubusercontent.com/18115603/219325343-4cc2b659-217d-40b8-9a95-94203c454046.png)

**Comment by youweimao** [comment]
database=configcenter;data source=XXXX;User Id=root;password=XXXX;port=3306;

**Comment by kklldog** [comment]
默认的mysql对高版本的mysql支持有点问题，搞笑的是这个驱动是 Oracle 官方提供的。
可以使用 agile_config:mysqlconnector 这个 tag 的镜像试试，用的三方的驱动。
