### ISSUE TITLE
环境同步时，描述项没有同步过去

### ISSUE THREAD

**Issue by 397419** [dotnetcore/AgileConfig#122]
能否在同步那里加一行代码，把描述项也同步下?
另：导入导出的json里面也没描述项。
                        // 如果有了相同的键，如果值不同，则更新
                        if (envConfig.Value != currentEnvConfig.Value)
                        {
                            envConfig.UpdateTime = DateTime.Now;
                            envConfig.Value = currentEnvConfig.Value;
                            if (envConfig.EditStatus == EditStatus.Commit)
                            {
                                envConfig.EditStatus = EditStatus.Edit;
                            }
                            **envConfig.Description = currentEnvConfig.Description;**        <---加这一行
                            envConfig.OnlineStatus = OnlineStatus.WaitPublish;
                            updateRanges.Add(envConfig);
                        }

**Comment by kklldog** [comment]
确实好像少了这一行，你都找到这了，你可以直接PR上来啊。省的我自己修了。。。
json的注释有点麻烦，得花时间搞了。

**Comment by kklldog** [comment]
thanks
