### ISSUE TITLE
配置项是否可以增加xml编辑功能？

### ISSUE THREAD

**Issue by libzlibz** [dotnetcore/AgileConfig#127]
c#配置有一些复杂的还是使用xml，看起来好像没有xml编辑功能

**Comment by kklldog** [comment]
XML 太复杂了，没办法简单的对应到 key value 模型。

**Comment by dengyangxi** [comment]
可以使用Newtonsoft.Json包将XML转换为JSON。这个包是一个流行的JSON框架，它提供了许多有用的功能，包括将XML转换为JSON。

以下是一个示例代码，演示如何将XML转换为JSON：

```
string xml = "<Test><Name>Test class</Name><X>100</X><Y>200</Y></Test>";
XmlDocument doc = new XmlDocument();
doc.LoadXml(xml);
string json = Newtonsoft.Json.JsonConvert.SerializeXmlNode(doc);
Console.WriteLine("XML -> JSON: {0}", json);
```
如果您想将JSON转换回XML，则可以使用以下代码：

```
string json = "{\"Test\":{\"Name\":\"Test class\",\"X\":\"100\",\"Y\":\"200\"}}";
XmlDocument doc = (XmlDocument)Newtonsoft.Json.JsonConvert.DeserializeXmlNode(json);

Console.WriteLine("JSON -> XML: {0}", doc.InnerXml);
```

此外，还有其他一些库可以将XML转换为JSON，例如System.Runtime.Serialization.Json和System.Xml.Linq。但是，Newtonsoft.Json是最受欢迎的库之一，因为它提供了许多有用的功能和灵活性。

**Comment by kklldog** [comment]
> 可以使用Newtonsoft.Json包将XML转换为JSON。这个包是一个流行的JSON框架，它提供了许多有用的功能，包括将XML转换为JSON。
> 
> 以下是一个示例代码，演示如何将XML转换为JSON：
> 
> ```
> string xml = "<Test><Name>Test class</Name><X>100</X><Y>200</Y></Test>";
> XmlDocument doc = new XmlDocument();
> doc.LoadXml(xml);
> string json = Newtonsoft.Json.JsonConvert.SerializeXmlNode(doc);
> Console.WriteLine("XML -> JSON: {0}", json);
> ```
> 
> 如果您想将JSON转换回XML，则可以使用以下代码：
> 
> ```
> string json = "{\"Test\":{\"Name\":\"Test class\",\"X\":\"100\",\"Y\":\"200\"}}";
> XmlDocument doc = (XmlDocument)Newtonsoft.Json.JsonConvert.DeserializeXmlNode(json);
> 
> Console.WriteLine("JSON -> XML: {0}", doc.InnerXml);
> ```
> 
> 此外，还有其他一些库可以将XML转换为JSON，例如System.Runtime.Serialization.Json和System.Xml.Linq。但是，Newtonsoft.Json是最受欢迎的库之一，因为它提供了许多有用的功能和灵活性。


那你问问 gpt ，attribute 怎么搞？
```
<text><name header="abc">X</name></text>
```

**Comment by NingLiu1998** [comment]
> 可以使用Newtonsoft.Json包将XML转换为JSON。这个包是一个流行的JSON框架，它提供了许多有用的功能，包括将XML转换为JSON。
> 
> 以下是一个示例代码，演示如何将XML转换为JSON：
> 
> ```
> string xml = "<Test><Name>Test class</Name><X>100</X><Y>200</Y></Test>";
> XmlDocument doc = new XmlDocument();
> doc.LoadXml(xml);
> string json = Newtonsoft.Json.JsonConvert.SerializeXmlNode(doc);
> Console.WriteLine("XML -> JSON: {0}", json);
> ```
> 
> 如果您想将JSON转换回XML，则可以使用以下代码：
> 
> ```
> string json = "{\"Test\":{\"Name\":\"Test class\",\"X\":\"100\",\"Y\":\"200\"}}";
> XmlDocument doc = (XmlDocument)Newtonsoft.Json.JsonConvert.DeserializeXmlNode(json);
> 
> Console.WriteLine("JSON -> XML: {0}", doc.InnerXml);
> ```
> 
> 此外，还有其他一些库可以将XML转换为JSON，例如System.Runtime.Serialization.Json和System.Xml.Linq。但是，Newtonsoft.Json是最受欢迎的库之一，因为它提供了许多有用的功能和灵活性。

你去看几眼复杂的xml类型

**Comment by kklldog** [comment]
暂时不会考虑支持 XML
