### ISSUE TITLE
发布配置存在BUG, 如果新建2个待发布的配置，选中其中1个，点击发布会将所有未发布的配置全部发布！~

### ISSUE THREAD

**Issue by dengyangxi** [dotnetcore/AgileConfig#128]
发布配置存在BUG:
         1. 新建2个**待发布**的配置，
         2. 选中其中**1个**，
         3. 点击发布
         4. 所有未发布的配置全部发布！~

![步骤](https://user-images.githubusercontent.com/30720784/228135045-798af45c-c320-4804-a24e-bed221dd440e.png)

**Comment by kklldog** [comment]
逻辑就是这样，发布不会受勾选影响，就是全部发布的。

**Comment by zeng09dong** [comment]
这个逻辑是有问题，看看apollo那逻辑非常好 想发布哪个就哪个 想同步哪个就哪个

**Comment by zeng09dong** [comment]
希望作者能改下这里的逻辑

**Comment by kklldog** [comment]
> 这个逻辑是有问题，看看apollo那逻辑非常好 想发布哪个就哪个 想同步哪个就哪个

那如果不勾选，是全部发布，还是一个都不发布？

**Comment by guochen2** [comment]
> > 这个逻辑是有问题，看看apollo那逻辑非常好 想发布哪个就哪个 想同步哪个就哪个
> 
> 那如果不勾选，是全部发布，还是一个都不发布？
@kklldog 
我觉得如果考虑用户易用性，两个方案
1.发布改为全部发布
2.若未选中任何一个，发布为不可点击状态，若有选中一个或多个，则发布选中的项

**Comment by kklldog** [comment]
https://github.com/dotnetcore/AgileConfig/releases/tag/v-1.6.16
已支持发布选择的项目
