### ISSUE TITLE
优先读取本地配置文件的内容还是站点配置内容

### ISSUE THREAD

**Issue by melody19930605** [dotnetcore/AgileConfig#129]

**Comment by kklldog** [comment]
一般来说站点内容是最优先的。这个其实取决于你configuration provider的顺序，后面的覆盖前面的。agileconfig也只是一个provider，如果你在agileconfig provider添加进去后又手动添加一个，那么这个最后添加的provider的优先级是最高的。

**Comment by melody19930605** [comment]
好的 明白了
