### ISSUE TITLE
User ID 字段过短

### ISSUE THREAD

**Issue by LiamSho** [dotnetcore/AgileConfig#141]
https://github.com/dotnetcore/AgileConfig/blob/d24dad99c490b0ee67d986e5ec37d472bc940920/src/AgileConfig.Server.Data.Entity/User.cs#L11-L12

这里限制了 User ID 字段长度为 <= 50

我使用 [Authentik](https://goauthentik.io) 作为 OIDC provider，默认使用哈希过的用户ID作为sub返回，长度64

不是很清楚当初为什么要限制50长度，大多数 OIDC provider 默认的sub好像都挺长的

这个 UserID 有长度限制可以注明一下，或者改长一点，现在在 Authentik 里我是吧 subject 模式改成了 UUID 来避免这个问题

**Comment by kklldog** [comment]
tag: v-1.7.1 已修改 user 表 id，name 长度为 256.
