### ISSUE TITLE
最新版的部署节点检测状态有问题？

### ISSUE THREAD

**Issue by robyle** [dotnetcore/AgileConfig#142]
![image](https://github.com/dotnetcore/AgileConfig/assets/11662528/0199ec53-9201-4050-b0f9-dc5e0acefd59)

为什么一直是离线状态？

**Comment by kklldog** [comment]
用 docker 跑？
-p 8501:5000 ?

**Comment by robyle** [comment]
> 用 docker 跑？ -p 8501:5000 ?

是的，莫非这样有问题？

**Comment by kklldog** [comment]
你用 docker 跑，注册节点 localhost:8501 是有问题的，因为 localhost 8501 代表你本地宿主机，容器内部是访问不到的，因为 localhost 在内部是代表容器自己。

**Comment by robyle** [comment]
> 你用 docker 跑，注册节点 localhost:8501 是有问题的，因为 localhost 8501 代表你本地宿主机，容器内部是访问不到的，因为 localhost 在内部是代表容器自己。

![image](https://github.com/dotnetcore/AgileConfig/assets/11662528/c91014c0-5f38-4156-b4ef-b92028a79cb2)
那用哪个地址？看着任何一个地址都不行，既然访问不到为什么又能等待一下后拿到更新信息呢？  这个逻辑视乎也说不通的

**Comment by kklldog** [comment]
> > 你用 docker 跑，注册节点 localhost:8501 是有问题的，因为 localhost 8501 代表你本地宿主机，容器内部是访问不到的，因为 localhost 在内部是代表容器自己。
> 
> ![image](https://user-images.githubusercontent.com/11662528/266833291-c91014c0-5f38-4156-b4ef-b92028a79cb2.png) 那用哪个地址？看着任何一个地址都不行，既然访问不到为什么又能等待一下后拿到更新信息呢？ 这个逻辑视乎也说不通的

用你的 内网 IP 试试。
能不能拿到配置跟你这个节点连不上没关系。这里只是控制台节点探测不到你配置的节点而已，探测的到探测不到你的节点物理上就是存在的。

**Comment by robyle** [comment]
> > > 你用 docker 跑，注册节点 localhost:8501 是有问题的，因为 localhost 8501 代表你本地宿主机，容器内部是访问不到的，因为 localhost 在内部是代表容器自己。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/11662528/266833291-c91014c0-5f38-4156-b4ef-b92028a79cb2.png) 那用哪个地址？看着任何一个地址都不行，既然访问不到为什么又能等待一下后拿到更新信息呢？ 这个逻辑视乎也说不通的
> 
> 用你的 内网 IP 试试。 能不能拿到配置跟你这个节点连不上没关系。这里只是控制台节点探测不到你配置的节点而已，探测的到探测不到你的节点都不影响物理上它就是存在的。

验了，视乎也没有用。我在Win11上拉起Docker跑的，视乎看着有bug，在另外一台Ubuntu虚拟机上走内网地址就没问题。

**Comment by kklldog** [comment]
也许跟你 docker 的网络配置有关系，如果你只有一个节点，你就用 localhost:5000 好了，让它自己探测自己。

**Comment by robyle** [comment]
> 也许跟你 docker 的网络配置有关系，如果你只有一个节点，你就用 localhost:5000 好了，让它自己探测自己。

哈哈，试了这个改成5000，确实起作用了。但是 根本问题没有解决，不可能一个应用固定一个端口。
