### ISSUE TITLE
应用Id为中文时有问题

### ISSUE THREAD

**Issue by tky753** [dotnetcore/AgileConfig#144]
问题1：
客户端 连接服务端 header 中 有个 appid，传的应用id，出现非ASCII字符，会报错：`Request headers must contain only ASCII characters.`，建议进行 `Uri.EscapeDataString` 处理

我修复了问题一，自己编译了一个客户端，发现还有以下问题：
问题2：
服务端发布修改后，客户端无法接收到reload通知

问题3：
websocket Action: Ping时，客户端计算出的md5总是和服务端传过来的不符合，导致每Ping一次就重新reload一次

服务端版本：1.7.1
客户端版本：基于1.7.0略有修改

附：
![image](https://github.com/dotnetcore/AgileConfig/assets/18205977/75b20e77-b0c1-46b3-b81c-b3b515213767)
![image](https://github.com/dotnetcore/AgileConfig/assets/18205977/cb55136f-d5fb-496b-9556-47f0d2814cbc)

**Comment by kklldog** [comment]
你这么一说好像中文的确实没测试过。我来试试。

**Comment by kklldog** [comment]
已解决中文id问题。
client >= 1.7.1
server >= 1.7.2
