### ISSUE TITLE
agileconfig在导入数据时，如果对应的value为空字符串报错

### ISSUE THREAD

**Issue by PengYouLin** [dotnetcore/AgileConfig#153]
我导入数据时，有一个如下配置：
"DisableContent": ""
显示导入失败，值不能为空。
但是在正式使用场景当中，会存在这种值。

**Comment by kklldog** [comment]
请问Agileconfig是什么版本？在页面底部有显示。
我记得这个问题已经修复过了。

**Comment by PengYouLin** [comment]
v1.5.7.6    Powered by .NET6.0 ant-design-pro4

**Comment by PengYouLin** [comment]
是不是要升到指定的版本以后才可以解决？麻烦告知一下版本号。

**Comment by kklldog** [comment]
> 是不是要升到指定的版本以后才可以解决？麻烦告知一下版本号。

太老了。更新到最新的1.8.1吧。不可能会缺字段，根据报错自己加1下吧。

**Comment by PengYouLin** [comment]
要不抽空更新一下kklldog/agile_config这个镜像？这个拉下来的还是1.5.3版本。

**Comment by kklldog** [comment]
> 要不抽空更新一下kklldog/agile_config这个镜像？这个拉下来的还是1.5.3版本。
那是你配置的本地的镜像没有同步好。
dockerhub：
https://hub.docker.com/layers/kklldog/agile_config/v-1.8.1/images/sha256-a03e893e5cc260eeff2cd04abef9a20fb6aadf13e6d892671d127ab6beb69503?context=explore

**Comment by PengYouLin** [comment]
![image](https://github.com/dotnetcore/AgileConfig/assets/71313757/d6ee2e2c-dca7-40d1-bbb8-efdfebbd6323)
这些建表语句，如果是在pgsql数据库环境下，默认是public的schema下的。可以暴露个参数出来，指定schema？
类似于这种
![image](https://github.com/dotnetcore/AgileConfig/assets/71313757/5720b982-2c43-45d2-8fea-17d2fcc7f96b)

**Comment by pengqian089** [comment]
>  这些建表语句，如果是在pgsql数据库环境下，默认是public的schema下的。可否暴露个参数出来，指定schema？ 类似于这种 

还挺麻烦的，如果指定了 schema，那么FreeSql就映射不到表名了。
除非 entity 改成 [Table(Name = "{schema}.{table_name}")]
考虑新建一个库？

**Comment by PengYouLin** [comment]
> > 这些建表语句，如果是在pgsql数据库环境下，默认是public的schema下的。可否暴露个参数出来，指定schema？ 类似于这种
> 
> 还挺麻烦的，如果指定了 schema，那么FreeSql就映射不到表名了。 除非 entity 改成 [Table(Name = "{schema}.{table_name}")] 考虑新建一个库？

不是，这里主要是影响建表，freesql的syncstructure额外指定schema的情况下，会把表建到public模式下面。查询的时候，根据你的数据库连接字符串，默认找账号的schema，如果不存在，再找public.
比如我有一个连接字符串“User ID=1111; Password=2222;Database=agileconfig”,要查询数据app表，默认是先查1111.app

**Comment by kklldog** [comment]
> > > 这些建表语句，如果是在pgsql数据库环境下，默认是public的schema下的。可否暴露个参数出来，指定schema？ 类似于这种
> > 
> > 
> > 还挺麻烦的，如果指定了 schema，那么FreeSql就映射不到表名了。 除非 entity 改成 [Table(Name = "{schema}.{table_name}")] 考虑新建一个库？
> 
> 不是，这里主要是影响建表，freesql的syncstructure不额外指定schema的情况下，会把表建到public模式下面。查询的时候，根据你的数据库连接字符串，默认找账号的schema，如果不存在，再找public. 比如我有一个连接字符串“User ID=1111; Password=2222;Database=agileconfig”,要查询数据app表，默认是先查1111.app

那账号schema下会出现 agc_app 表吗？如果不存在，那也应该没问题吧？

**Comment by PengYouLin** [comment]
> > > > 这些建表语句，如果是在pgsql数据库环境下，默认是public的schema下的。可否暴露个参数出来，指定schema？ 类似于这种
> > > 
> > > 
> > > 还挺麻烦的，如果指定了 schema，那么FreeSql就映射不到表名了。 除非 entity 改成 [Table(Name = "{schema}.{table_name}")] 考虑新建一个库？
> > 
> > 
> > 不是，这里主要是影响建表，freesql的syncstructure不额外指定schema的情况下，会把表建到public模式下面。查询的时候，根据你的数据库连接字符串，默认找账号的schema，如果不存在，再找public. 比如我有一个连接字符串“User ID=1111; Password=2222;Database=agileconfig”,要查询数据app表，默认是先查1111.app
> 
> 那账号schema下会出现 agc_app 表吗？如果不存在，那也应该没问题吧？

我就是想要实现把相应的表建在指定的schema下面的。

**Comment by kklldog** [comment]
> > > > > 这些建表语句，如果是在pgsql数据库环境下，默认是public的schema下的。可否暴露个参数出来，指定schema？ 类似于这种
> > > > 
> > > > 
> > > > 还挺麻烦的，如果指定了 schema，那么FreeSql就映射不到表名了。 除非 entity 改成 [Table(Name = "{schema}.{table_name}")] 考虑新建一个库？
> > > 
> > > 
> > > 不是，这里主要是影响建表，freesql的syncstructure不额外指定schema的情况下，会把表建到public模式下面。查询的时候，根据你的数据库连接字符串，默认找账号的schema，如果不存在，再找public. 比如我有一个连接字符串“User ID=1111; Password=2222;Database=agileconfig”,要查询数据app表，默认是先查1111.app
> > 
> > 
> > 那账号schema下会出现 agc_app 表吗？如果不存在，那也应该没问题吧？
> 
> 我就是想要实现把相应的表建在指定的schema下面的。

哦哦，那得看看 freesql 新版本是否改进了这个问题。

**Comment by kklldog** [comment]
在pg下，Schema好像可以在 connection string 上直接指定
