### ISSUE TITLE
[性能] 是否考虑支持 .Net8 AOT ？

### ISSUE THREAD

**Issue by Zhao-Michael** [dotnetcore/AgileConfig#154]
AgileConfig 资源占用还是挺大的，在一些资源紧缺的微型服务器上占大头了

**Comment by Zhao-Michael** [comment]
![image](https://github.com/dotnetcore/AgileConfig/assets/15730936/cbb6820c-d6f0-47d6-9b57-380958a0bf6c)

**Comment by kklldog** [comment]
一百多M还好吧。
AOT 根据没啥收益啊。论性能未必有JIT快，很多反射的代码还得改，也就内存可能会小一点，没啥动力。。

**Comment by ZUOXIANGE** [comment]
想要AOT可以试试https://github.com/r-nacos/r-nacos,我觉得他这个思路不错,就是能不能用于生产还有待观察
