### ISSUE TITLE
日志能否接入 Seq 或者 Exceptionless ?

### ISSUE THREAD

**Issue by pengqian089** [dotnetcore/AgileConfig#155]
不仅仅是系统日志，还包括 SysLog 的数据。

今天修改SysLog的时候，想到的。想把日志做统一管理。

而且日志也有时效性，太过久远的日志参考意义就不是很大了。

我目前使用的是 Seq ，相关的api都有了解

**Comment by kklldog** [comment]
Seq我也用，不过咱对接了Seq就变得特例了。
我想的是这部分日志可以写 log file，这是 agileconfig 的 scope。
至于后面用户可以用 Beats / logstash 等收集工具进其他日志管理组件。这样比较通用。
另外我看 OpenTelemetry 里也是有 logging 的规范，或许这也是个比较好的标准化的方案。
关于日志的时效性，确实可以设计一个配置项，指定保留多久的日志。
e.g. LogCycle = 6m

**Comment by a34546** [comment]
期待加入日志平台功能，主打轻量，这样不想部署日志服务了。

**Comment by kklldog** [comment]
> 期待加入日志平台功能，主打轻量，这样不想部署日志服务了。

hi，
后面可能会加入往外抛日志的功能，但是肯定不会直接加入日志服务（收集、展示）。这样就不轻量拉。。。跟 agileconfig 的初衷是相悖的。

**Comment by kklldog** [comment]
最新版本马上支持 opentelemetry。不光可以对外提供 logs，还有 traces and metrics。

**Comment by pengqian089** [comment]
> 最新版本马上支持 opentelemetry。不光可以对外提供 logs，还有 traces and metrics。敬请期待。

有什么是我可以帮的上的吗？

**Comment by kklldog** [comment]
请直接对接Opentelemetry
https://mp.weixin.qq.com/s/QoagvZrCby1jI6g3XzZUAg
