### ISSUE TITLE
如何关闭Trace 日志

### ISSUE THREAD

**Issue by Jesn** [dotnetcore/AgileConfig#158]
![image](https://github.com/dotnetcore/AgileConfig/assets/5728274/828133b0-170f-4c3b-82e3-d06a1bab973c)

全部都是Trace日志，影响查看，建议在安装的时候给一个配置日志级别的环境变量

**Comment by kklldog** [comment]
你说的是 client 侧的日志吧
logger默认是跟随系统日志的级别的，你可以修改 appsettings.json 
  "Logging": {
    "LogLevel": {
      "Default": "Trace",
      "System": "Information",
      "Microsoft": "Information"
    }
  }

**Comment by Jesn** [comment]
> 你说的是 client 侧的日志吧 logger默认是跟随系统日志的级别的，你可以修改 appsettings.json "Logging": { "LogLevel": { "Default": "Trace", "System": "Information", "Microsoft": "Information" } }

设置了，无效
![image](https://github.com/dotnetcore/AgileConfig/assets/5728274/6289cb1d-07ae-47a3-b17e-f0ed403ea128)

**Comment by Jesn** [comment]
> 你说的是 client 侧的日志吧 logger默认是跟随系统日志的级别的，你可以修改 appsettings.json "Logging": { "LogLevel": { "Default": "Trace", "System": "Information", "Microsoft": "Information" } }

设置了，无效
![image](https://github.com/dotnetcore/AgileConfig/assets/5728274/6289cb1d-07ae-47a3-b17e-f0ed403ea128)

**Comment by kklldog** [comment]
你是怎么使用的，如果是使用 AddAgileConfig 肯定是有效的。
如果是手动new，那就主机给 Logger 属性赋值

**Comment by Jesn** [comment]
我是用的  `AddAgileConfig`

![image](https://github.com/dotnetcore/AgileConfig/assets/5728274/b895a4d4-9a79-4625-9b46-b9971b2ed838)




![image](https://github.com/dotnetcore/AgileConfig/assets/5728274/4a9d817c-3ecd-49f0-917d-1d5c6f5e99c5)

**Comment by kklldog** [comment]
如果没啥特殊需求，请用 UseAgileConfig。或者 ConfigClient.Instance.Logger = your logger 手动赋值一个 logger
