### ISSUE TITLE
async 不需要await 的场景下是否可以直接返回 Task 结果？减少async 编译器压力呢？

### ISSUE THREAD

**Issue by HaoQianCheng** [dotnetcore/AgileConfig#160]
![image](https://github.com/dotnetcore/AgileConfig/assets/86709205/3e2f966b-a338-4679-a1f5-b38134543407)

![image](https://github.com/dotnetcore/AgileConfig/assets/86709205/3db34bf3-d69d-425d-9253-671ced6f55d3)

**Comment by kklldog** [comment]
总体上没啥区别，但是确实是直接 return task 更好一点。
