### ISSUE TITLE
System.IdentityModel.Tokens.Jwt 7.0.3 漏洞问题

### ISSUE THREAD

**Issue by HaoQianCheng** [dotnetcore/AgileConfig#163]
漏洞：
https://github.com/advisories/GHSA-8g9c-28fc-mcx2
https://github.com/advisories/GHSA-8g9c-28fc-mcx2

**Comment by HaoQianCheng** [comment]
简易作者应该将 System.IdentityModel.Tokens.Jwt 包升级为 >7.1.2 以上版本

**Comment by kklldog** [comment]
你提 PR 吧。
