### ISSUE TITLE
pgsql ssl连接异常

### ISSUE THREAD

**Issue by 892513490** [dotnetcore/AgileConfig#165]
pgsql ssl连接时，抛出如下异常：
Npgsql.PostgresException (0x80004005): 28000: no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "postgres", database "agile-config", no encryption

经测试，ado.net和freesql都能正常连接及执行sql，但是agileconfig项目运行抛错

**Comment by kklldog** [comment]
你连接串发出来看看呢
