### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by agileboy365** [dotnetcore/AgileConfig#167]
System.UnauthorizedAccessException: Access to the path '/app/pkmaster.agileconfig.client.configs.cache' is denied
docker打包镜像，使用非root账号保存缓存因为权限问题会失败，可以配置缓存不保存文件吗，k8s之类的部署配置缓存到文件里是没啥意义的，容器不会多次启动

**Comment by kklldog** [comment]
这个异常并不会影响其他功能。有空加个开关。

**Comment by agileboy365** [comment]
异常对日志的有影响，执行的频率高，产生的日志有点多

**Comment by kklldog** [comment]
最新版支持这个参数 cache:enabled

**Comment by agileboy365** [comment]
非常感谢
