### ISSUE TITLE
非容器对象中如何独立单次获得配置引用

### ISSUE THREAD

**Issue by supersdar** [dotnetcore/AgileConfig#171]
我在外面写了一个模块插件，本来这个插件里是直接通过ConfigurationManager读取appsetting的配置来获得ip
换AgileConfig在这里不知道该怎么读取。
我在想是否写个静态配置Helper类，先在主程序中预存参数后在这里使用。

**Comment by kklldog** [comment]
ConfigurationManager？难道是.NET FRAMEWORK？

**Comment by supersdar** [comment]
除了IConfiguration，.net core中不是一直可以直接ConfigurationManager.AppSettings["Connstr"]读取到app setting.json.

**Comment by supersdar** [comment]
agileconfig能不能也这样，就像读取本地清单那样直接一个代码读取。说真的其实很多项目也用不上websocket来持续监听最新配置。用agileConfig就只是为了简单替换appsettings.json，免去每个系统复制黏贴覆盖appsettings.json
