### ISSUE TITLE
升级.net6 之后，，agileconfig onreload 事件会每30秒触发一次，，导致大量无效日志

### ISSUE THREAD

**Issue by kasenhoo** [dotnetcore/AgileConfig#172]
代码如下：
![image](https://github.com/dotnetcore/AgileConfig/assets/3382561/f423bd88-1aa3-4426-85f7-19d0b4b08d4e)

产生的无效日志如下： 
![image](https://github.com/dotnetcore/AgileConfig/assets/3382561/5c3de43c-8224-4c35-8c72-305e2982471c)

查了好久，，发现这里有30秒心跳，，
![image](https://github.com/dotnetcore/AgileConfig/assets/3382561/23078de1-7f67-45ad-a127-b44b3e6eade5)

不清楚是.net6的问题，还是agileconfig的问题，，搞不定。。

按上面的说法，是hash不同导致的，，，可是啥都没做。。
 
agileconfig版本， docker部署。
![image](https://github.com/dotnetcore/AgileConfig/assets/3382561/5e7b1a38-9bf5-4fcb-a9ca-1203b6b25711)

然而，3.1 sdk没这个问题。

**Comment by kklldog** [comment]
先把 server 跟 client 都更新到最新版本再试试
