### ISSUE TITLE
编辑json的时候，如果配置项是数组，会出现新增情况

### ISSUE THREAD

**Issue by PengYouLin** [dotnetcore/AgileConfig#178]
部署版本：v1.8.0.0 
我有个如下数组：
{
  "test": [
    "1",
    "2"
  ]
}
里面准备再添加一个"3"
![image](https://github.com/dotnetcore/AgileConfig/assets/71313757/d9672993-deac-4979-b5df-9d689eb30804)
点击保存后得到的结果：
![image](https://github.com/dotnetcore/AgileConfig/assets/71313757/822c9269-d24d-4b08-ad08-c61bb9c7749e)

**Comment by kklldog** [comment]
我试了下，好像并不会。如果
```
 {
"test": [
"1",
"2"
]
}
```
也是直接通过 json 编辑模式生成的话，应该都是一致的。
另外其实你这样也无所谓，因为最终得到的结果是一样的。
