### ISSUE TITLE
前端查询时很容易报错，简单修复如下

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/AgileConfig#200]
![image](https://github.com/user-attachments/assets/33529ad6-a8ac-48b4-82b9-b5a880699947)
![image](https://github.com/user-attachments/assets/cfce5cc5-fa95-496d-ba3a-4ea5a991ec77)

**Comment by kklldog** [comment]
有空看下，好像是重构除问题了

**Comment by kklldog** [comment]
已经修复 #202
