### ISSUE TITLE
当作为服务注册中心时，发现问题如下

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/AgileConfig#201]
1. 某服务A(服务名admin)异常，不执行`ConfigClient.Instance?.DisconnectAsync()`（未正常退出的情况下）, 在agile服务中心，一直显示异常。-- 该服务至少 6个小时 没有启动过了，还一直以异常的形式存在。
并且其他子服务B，通过agile client `IDiscoveryService`，查找admin服务时，`discovery.GetByServiceName("admin")` 或者 `discovery.Services`，都会带有该已下线的服务
这不便于默认使用，总是会访问到已失效的服务。  我感觉应该这样
>1 服务端 对异常服务 默认超过2个检查周期(可手动配置异常删除时间)就彻底删除服务
>2 客户端之前已有的和服务相关的api，获取到的应该全部都是健康的服务。   此外单独提供一个api，用户可以强制查看查看当前未被删除的，不管健康或不健康的服务列表

![image](https://github.com/user-attachments/assets/3bd78e8f-7adb-4cf0-9054-1fb9527963b8)
![image](https://github.com/user-attachments/assets/7d1c78ac-ea62-4a5c-86a6-ed83a8f7e9eb)

**Comment by yangbocheng** [comment]
牛的大佬
问题1  确实有该配置可以解决问题
问题2  IDiscoveryService中确实已有HealthyServices，UnHealthyServices等api。  但是DiscoveryServiceExtension里面的GetByServiceName， GetByServiceId， RandomOne等是否最好默认从HealthyServices中获取？    实际的业务场景是肯定不想访问不健康的服务。 
![image](https://github.com/user-attachments/assets/d8729ebe-bc32-46d5-96a3-e44cac9d7586)

![image](https://github.com/user-attachments/assets/08eb70ac-99df-48be-afb7-61a2ba1a3e41)

**Comment by kklldog** [comment]
有的时候根据id，或者 name去查服务也不是为了调用。
这个你自己下扩展方法超级简单的，我改的话，可能是 breaking change 会影响其他人的。

**Comment by yangbocheng** [comment]
好的。 谢谢！
