### ISSUE TITLE
建议提供文本框粘贴json批量生成配置的功能

### ISSUE THREAD

**Issue by NKidding** [dotnetcore/AgileConfig#32]
现有的是导入json文件的方式批量导入配置，建议弹出一个文本框，粘贴想生成配置的json批量生成，这样方便很多
另外建议提供复制项目配置的功能

**Comment by kklldog** [comment]
可以考虑，以后再说。

**Comment by kklldog** [comment]
v-1.5.4 已经支持 json 编辑模式，可以直接把json文本复制进去 @NKidding
