### ISSUE TITLE
缓存文件怎么配置路径

### ISSUE THREAD

**Issue by caopengfei** [dotnetcore/AgileConfig#42]
程序运行后，会在根目录生成“xxx.agileconfig.client.configs.cache”这样的缓存文件，这个文件的路径有办法配置吗？因为一方面生成在根目录，如果缓存文件多的话，看起来就很乱了，这个存储在特定的文件夹，比如根目录的cache文件夹，方便统一管理；还有就是如果是docker部署的，重新启动容器后，.cache文件就全都丢失了。

**Comment by kklldog** [comment]
目前不支持指定存储目录，非常好的建议。要不你改一下存储在固定的目录 /agileconfig_cache ，这样也可以通过 -v 映射出去

**Comment by dengyangxi** [comment]
强烈建议下个版本 将现在默认路径 ：     bin/*.agileconfig.client.configs.cache   改成默认路径：  bin/agileconfig_cache/*.agileconfig.client.configs.cache

最好能提供参数 支持 自定义， 缓存文件存储目录。

**Comment by kklldog** [comment]
> 强烈建议下个版本 将现在默认路径 ： bin/_.agileconfig.client.configs.cache 改成默认路径： bin/agileconfig_cache/_.agileconfig.client.configs.cache
> 
> 最好能提供参数 支持 自定义， 缓存文件存储目录。

这个需求已经有兄弟在做了，等他pr上来

**Comment by QQ897878763** [comment]
@dengyangxi @caopengfei 最新的AgileConfig_Client v1.2.1.7已解决 可以查看READ.ME配置
