### ISSUE TITLE
移除配置命名空间, 允许配置项直接调用.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnetcore/AgileConfig#43]
![image](https://user-images.githubusercontent.com/16236903/129655102-2005b893-a601-441b-9d0c-0c4c3ecaf6a5.png)
允许 `config.AddAgileConfig();` 不引用命名空间即可调用.

**Comment by NMSAzulX** [comment]
![image](https://user-images.githubusercontent.com/16236903/129655360-9edaa2fa-b62d-416e-b3c2-1a655777bf2e.png)

**Comment by kklldog** [comment]
是不是应该是 IConfigurationBuilder 的 ns 保持一致。
另外我发现，AgileConfig 中间怎么多了个 . ，晕死

**Comment by NMSAzulX** [comment]
委托作为参数使用时可以忽略命名空间的, 除非已经引用了  IConfigurationBuilder 的命名空间, 否则就算与  IConfigurationBuilder 保持一直也不能 . 出来.   现在很多初始化配置都不需要使用 ns 了.

**Comment by kklldog** [comment]
要不你给client pr 一下 。

**Comment by NMSAzulX** [comment]
好

**Comment by kklldog** [comment]
你先更新一下，昨天我改了点东西，免的到时候合并。
