### ISSUE TITLE
数据库未生成

### ISSUE THREAD

**Issue by imtudou** [dotnetcore/AgileConfig#54]
大佬，我是下载publish分支源码进行编译使用的，配置的数据库连接，好像没有生成对应的表，不知道是不是我操作姿势不对
![1631869787052_D844AAF0-C8A2-4b80-A858-84D5D851D304](https://user-images.githubusercontent.com/37775915/133757053-9604de27-9569-446b-b01d-7aadcf20058e.png)

**Comment by kklldog** [comment]
sqlserver 小写。

**Comment by imtudou** [comment]
那如果是小写的话想问一下那些账号信息你是存储到哪里了哦 我找了半天都没找到
![image](https://user-images.githubusercontent.com/37775915/133757394-0eaec804-399c-4e49-b933-4028bea86aa5.png)

**Comment by kklldog** [comment]
连接串上啊，你现在的连接串用的是集成登录。。。你要还个方式。

**Comment by kklldog** [comment]
//"provider": "sqlserver", 
    //"conn": "Persist Security Info = False; User ID =dev; Password =dev@123; Initial Catalog =agile_config; Server =192.168.18.82"

**Comment by imtudou** [comment]
可是我还是想请教一下当我这边连接字符串配置的有问题的时候你把配置 中心的数据存储到哪里呀

**Comment by kklldog** [comment]
或许默认用的sqlite，可能在bin目录下
