### ISSUE TITLE
配置项发布以后如果站点不重启 配置项无法生效？

### ISSUE THREAD

**Issue by wangchaoit** [dotnetcore/AgileConfig#56]
配置项发布以后如果站点不重启 配置项无法生效？

**Comment by kklldog** [comment]
可以的，你先确定下你的client跟节点的websocket连接建立了没有，节点加入控制台了没有。

**Comment by wangchaoit** [comment]
> 可以的，你先确定下你的client跟节点的websocket连接建立了没有，节点加入控制台了没有。

感谢回复 ， 我在测试的时候发现好像没法生效不知道是不是哪里出了问题

**Comment by kklldog** [comment]
控制台的客户端才菜单里能看到你连接的client吗

**Comment by wlclass** [comment]
> > 可以的，你先确定下你的client跟节点的websocket连接建立了没有，节点加入控制台了没有。
> 
> 感谢回复 ， 我在测试的时候发现好像没法生效不知道是不是哪里出了问题

你说的站点不重启,是指客户端重启才生效吧.
如果是的话,那是客户端读配置的方式不对,
