### ISSUE TITLE
你这开源也太潦草了把

### ISSUE THREAD

**Issue by ysq5202121** [dotnetcore/AgileConfig#57]
1.关于项目结构希望还是能够描述清楚
2.关于前后端分离，建议两个项目，一个前端一个后端.
3.关于发行版本，可以直接编译出来
4.前后端具体的编译也可以稍微介绍下.

**Comment by kklldog** [comment]
仔细看readme_cn

**Comment by kklldog** [comment]
AgileConfig.Server.UI 这都看不出来是前端项目，那我也没辙。这不是标准的前后端分离项目，为了简化部署，ui编译后会需要混合在后端项目做为静态资源发布（当然不嫌麻烦的话，也可以分开部署）。发行版已经推送到 dockerhub ，要IIS自己部署的，那就自己折腾吧，编译已经很简单了，直接vs发布就可以，关于前端项目的编译，会的自然会，不会的关于node npm 的东西也不是一句两句说的明白的。
饭是喂不完的。

**Comment by ysq5202121** [comment]
> @ysq5202121 开源潦草你倒是开源一个看看呢？就知道嘴张开了别人给你喂？
我大概的意思是希望作者写一个大纲一样的东西稍微介绍一下，比如前端相关的一些信息，使用了什么，怎么开启，在什么位置，等一个流程，文档工作量不会太大，这样对于软件的散播是有好处的，好的开源软件总是让人可以快速的上手，，我想任何做开源的总希望又更多的人使用自己的产品，我说的话是不好听，但是确实做好对开源有好处（前后端我都会，同样花费大量时间去查找和研究这个，才运行正常）。

**Comment by ysq5202121** [comment]
> AgileConfig.Server.UI 这都看不出来是前端项目，那我也没辙。这不是标准的前后端分离项目，为了简化部署，ui编译后会需要混合在后端项目做为静态资源发布（当然不嫌麻烦的话，也可以分开部署）。发行版已经推送到 dockerhub ，要IIS自己部署的，那就自己折腾吧，编译已经很简单了，直接vs发布就可以，关于前端项目的编译，会的自然会，不会的关于node npm 的东西也不是一句两句说的明白的。 饭是喂不完的。

能有项目的相关简介终归是对开源有好处

**Comment by kklldog** [comment]
> > AgileConfig.Server.UI 这都看不出来是前端项目，那我也没辙。这不是标准的前后端分离项目，为了简化部署，ui编译后会需要混合在后端项目做为静态资源发布（当然不嫌麻烦的话，也可以分开部署）。发行版已经推送到 dockerhub ，要IIS自己部署的，那就自己折腾吧，编译已经很简单了，直接vs发布就可以，关于前端项目的编译，会的自然会，不会的关于node npm 的东西也不是一句两句说的明白的。 饭是喂不完的。
> 
> 能有项目的相关简介终归是对开源有好处

[中文readme](https://github.com/dotnetcore/AgileConfig/blob/master/README_CN.md) 感觉写的太清晰了吧，改天把默认readme设置成CN的。

**Comment by alexinea** [comment]
> > AgileConfig.Server.UI 这都看不出来是前端项目，那我也没辙。这不是标准的前后端分离项目，为了简化部署，ui编译后会需要混合在后端项目做为静态资源发布（当然不嫌麻烦的话，也可以分开部署）。发行版已经推送到 dockerhub ，要IIS自己部署的，那就自己折腾吧，编译已经很简单了，直接vs发布就可以，关于前端项目的编译，会的自然会，不会的关于node npm 的东西也不是一句两句说的明白的。 饭是喂不完的。
> 
> 能有项目的相关简介终归是对开源有好处

Complaining is not helpful. If you think the project can be improved further, then you can submit a PR for us.

Thank you for your attention to our project :)
