### ISSUE TITLE
建议添加环境配置和多重继承的支持

### ISSUE THREAD

**Issue by NetChenQian** [dotnetcore/AgileConfig#60]
### 1. 环境配置

当前没有环境的概念，支持环境的配置后可以很方便地在不同的部署环境下切换配置；
可分开发环境、测试环境和生产环境，类似于 appsettings.json，appsettings.Development.json的关系。

### 2. 多重继承

当前只有两个层级，支持多重继承可以提高配置的复用。
子配置可以继承父配置，孙子配置可以继承子配置等，没有继承层级的限制，或者最多能支持到3~5层配置。

**Comment by kklldog** [comment]
1. 很多人都提了这个需求，有空加上吧。其实我觉得生产跟其他环境都部署在一起，这样合适么。。
2. 这个多层次继承我怕搞的很混乱。

**Comment by bc4250** [comment]
多级继承可以在编辑画面看到哪些是继承， 哪些是被覆盖的的吗， 目前UI上看不到.

**Comment by kklldog** [comment]
> 多级继承可以在编辑画面看到哪些是继承， 哪些是被覆盖的的吗， 目前UI上看不到.

我也觉得需要展示一下，计划中。

**Comment by kklldog** [comment]
link to https://github.com/dotnetcore/AgileConfig/issues/58
