### ISSUE TITLE
手动新建了数据库，但是表不会自动生成

### ISSUE THREAD

**Issue by igaobingbing** [dotnetcore/AgileConfig#69]
手动新建了数据库，但是表不会自动生成

**Comment by kklldog** [comment]
把原来的数据库的agc_app表名改一下，程序以为已经建过了。

**Comment by igaobingbing** [comment]
我创建的agileConfig是空数据库哦，运行docker安装程序安装成功了，数据库还是空的，打开UI就报错了

**Comment by igaobingbing** [comment]
使用的是:latest版本

**Comment by kklldog** [comment]
你是不是以前跑过，所以已经建过表了。mysql 检测是否建表会搜索整个mysql实例，如果你已经有一个数据库里有了acg_app它就不会建了。

**Comment by igaobingbing** [comment]
明白了，MySQL下确实存在老版本的库。
