### ISSUE TITLE
docker中.net5连接sqlserver出错报错误

### ISSUE THREAD

**Issue by lccclclclclclclcl** [dotnetcore/AgileConfig#71]
docker中.net5连接sqlserver出错报错误【主库】仍然不可用，下一次恢复检查时间：12/10/2021 17:34:43，错误：(A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught))

原因好像是因为未在Dockerfile中添加
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf
所导致的..可以麻烦大佬加下配置吗？低版本的sqlserver不支持TLSv1.2需要降低为 TLSv1

**Comment by kklldog** [comment]
我没环境不好测，我怕影响到其它用户。你自己改改，自己打包一下好了啊。

**Comment by kklldog** [comment]
dockerfile都在源码里

**Comment by kklldog** [comment]
我加上这些
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /usr/lib/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf

sqlserver 2012 还是连不上 我靠。

**Comment by kklldog** [comment]
我搞定了，最新的镜像指定 tslv1 了 ，测试下来 sqlserver2012 没有问题了。
对了，连接串可能要指定 Encrypt=True;TrustServerCertificate=True; 不然还是可能报证书错误的问题。
