### ISSUE TITLE
建议增加PathBase参数

### ISSUE THREAD

**Issue by tracyma-05** [dotnetcore/AgileConfig#78]
在部署的时候，增加PathBase参数，不然nginx反向代理不好配置

**Comment by kklldog** [comment]
不太明白具体问题
http://agileconfig_server.xbaby.xyz/ 这个演示站点就是nginx代理的，好像没啥问题

**Comment by tracyma-05** [comment]
> 不太明白具体问题 http://agileconfig_server.xbaby.xyz/ 这个演示站点就是nginx代理的，好像没啥问题

比如我要设置的URL是 https://www.xxx.top/agile 代理到该服务，跳转之后，页面会重定向到  https://www.xxx.top/ui  这样就会有问题了。

nginx 设置为    
```
location /agile/ {
        proxy_pass        http://127.0.0.1:15001/;
    }
```

**Comment by kklldog** [comment]
明白了，我处理一下。

**Comment by kklldog** [comment]
更新latest or v-1.5.7.8
新增配置项 pathBase

-e pathBase=test

location /test {
        proxy_pass        http://127.0.0.1:15001;
    }

测试 http://agileconfig_server.xbaby.xyz/test
