### ISSUE TITLE
1.2.1.7 升级至 1.2.1.9 异常 Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ClueeZhuo** [dotnetcore/AgileConfig#80]
![360截图20220315165359279](https://user-images.githubusercontent.com/9359405/158341512-acc8864d-975b-4c97-b30c-a7e40b1d1263.jpg)

**Comment by kklldog** [comment]
异常的明细点出来看看？
.net core 版本多少？
program.cs 那边的代码是怎么样的？

**Comment by ClueeZhuo** [comment]
var builder = WebApplication.CreateBuilder(args).Inject();
builder.Host
    .UseSerilogDefault(config =>
    {
        config.Enrich.FromLogContext()
              .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}")
              .WriteTo.File($"{AppContext.BaseDirectory}Log/.log", rollingInterval: RollingInterval.Day, rollOnFileSizeLimit: true, outputTemplate: "{Timestamp:HH:mm} || {Level} || {SourceContext:l} || {Message} || {Exception} ||end {NewLine}");
    })
    .ConfigureAppConfiguration((context, config) =>
    {
        config.AddAgileConfig((arg) =>
        {
            Console.WriteLine($"action:{arg.Action} key:{arg.Key}");
        });
    });

var app = builder.Build();
app.MapControllers();
app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();

**Comment by ClueeZhuo** [comment]
.net6.0

**Comment by ClueeZhuo** [comment]
![image](https://user-images.githubusercontent.com/9359405/158344707-49006b32-3c00-4d79-9081-bbfc5ded59d0.png)

**Comment by kklldog** [comment]
你这 net6 怎么又有program 又有startup啊 。
net6 你可以参考 https://github.com/kklldog/AgileConfig_Client/blob/master/AgileConfigMVCSampleNET6/Program.cs
```
using Serilog;

var builder = WebApplication.CreateBuilder(args);
builder.Host.UseSerilog((ctx, lc) => lc
    .WriteTo.Console()
    );
//use agileconfig client
builder.Host.UseAgileConfig();

// Add services to the container.
builder.Services.AddRazorPages();

var app = builder.Build();
// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
}
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();
```
使用 UseAgileConfig 方法， services.AddAgileConfig 可以不用手写了。已经在use方法里调用过了。

**Comment by ClueeZhuo** [comment]
完美，么么哒。。。
