### ISSUE TITLE
应用引用AgileConfig后，注册到window服务启动报错

### ISSUE THREAD

**Issue by AllanHao** [dotnetcore/AgileConfig#81]
基于.net6开发了一个WorkerService。引入AgileConfig后，发出程序，并注册到window服务后，启动服务报错。
报错信息如下：
![image](https://user-images.githubusercontent.com/3953310/158712231-9ac04273-0b03-4d4d-b677-8d22c2a4a3a6.png)

注册AgileConfig代码如下：
![image](https://user-images.githubusercontent.com/3953310/158712272-ea6056bb-8771-41c6-8006-61f9b8f44d84.png)

创建windows服务命令如下：
`sc.exe create ModbusWorkerService binPath= E:\Project\WorkerService\WorkerService\bin\Release\net6.0\publish\WorkerService.exe`

去掉Program.cs中注册AgileConfig的代码，则一切正常。

**Comment by kklldog** [comment]
不作为服务，直接跑是可以的吗？

**Comment by kklldog** [comment]
作为服务启动的时候可能根目录会定位到system目录下，所以可能是启动的时候找不到配置文件造成的。你可以试试ConfigurationBuilder来构造一个iconfiguration对象：
```
1.使用var builder = new ConfigurationBuilder() 拿到iconfiguration对象，
var client = new ConfigClient(configuartion);
builder.UseAgileConfig(client, e => e.Action);
```

**Comment by kklldog** [comment]
我修复了这个问题，新版本已经兼容了windows服务路径的问题。直接更新最新的 1.2.1.10 的包。

**Comment by AllanHao** [comment]
谢谢，大佬，我测试一下。

**Comment by AllanHao** [comment]
1.2.1.10版本测试通过，没有问题了，谢谢。
