### ISSUE TITLE
如何从1.3升级到1.5

### ISSUE THREAD

**Issue by tiansfather** [dotnetcore/AgileConfig#84]
最早是在用1.2的，后来找到1.2升级1.3的数据库升级文档升级到1.3了，
现在想升级到1.5,但目前只找到了1.4升级1.5的说明，而1.4比1.3多了几个表，请问应该如何升级？
放了十几个应用配置在上面，怕出乱子

**Comment by kklldog** [comment]
跨度太大，建议你使用最新的版本直接在一个新库上生成表结构，然后1.3使用导出json功能，再导入到新的库里。这样可能比较简单。

**Comment by tiansfather** [comment]
sure
