### ISSUE TITLE
支持 nodejs 访问服务么

### ISSUE THREAD

**Issue by wwq3021** [dotnetcore/AgileConfig#85]
希望添加nodejs 或 其他语言的 AgileConfig.Client 包

**Comment by kklldog** [comment]
目前就是.net的client。有空我可以搞一下。
大家一起动手丰衣足食嘛，我哪有那么多时间啊。

**Comment by LetTTGACO** [comment]
> 目前就是.net的client。有空我可以搞一下。 大家一起动手丰衣足食嘛，我哪有那么多时间啊。

说的挺对，实际行动令人堪忧。我本来想加群了解下，顺便做一个Node版本的客户端的，结果加群还要回到什么是CLR，我不了解，就拒绝让我加群。。。这是开源的态度吗？

**Comment by LetTTGACO** [comment]
> 希望添加nodejs 或 其他语言的 AgileConfig.Client 包

我写了一个，本地测试正常，但目前还没应用接入实战测试，可以试一试：https://github.com/LetTTGACO/node-agile-client
