### ISSUE TITLE
配置或服务发生变更时，应用如何监听

### ISSUE THREAD

**Issue by gonghuilie** [dotnetcore/AgileConfig#86]
配置或服务发生变更时，应用如何监听?

**Comment by kklldog** [comment]
服务端配置变化的时候会实时刷新client的配置同时触发change事件，但是监听不到具体哪个项目变化了。如果要监听具体哪个项目变化了，可以使用core配置系统的IOptionsMonitor模式进行监听。
服务还是预览版，没有对应的change事件抛出。

**Comment by kklldog** [comment]
服务发现现在会对外抛一个时间 DiscoveryService.ReLoaded 事件，当服务状态发生变化的时候。
