### ISSUE TITLE
服务注册与发现,无法自动注册

### ISSUE THREAD

**Issue by CQ-Wangrz** [dotnetcore/AgileConfig#87]
我看文档在配置中添加节点
"AgileConfig": {
    "appId": "test001", 
    "secret": "123456", 
    "nodes": "http://119.84.112.137:15000", 
    "name": "client_test1", 
    "tag": "test1", 
    "env": "TEST", 
    "serviceRegister": { 
      "serviceId": "testService1", 
      "serviceName": "测试注册服务", 
      "ip": "127.0.0.1", 
      "port": 5005
    }
  }
但是在服务页面没有注册的信息,查看控制台websocket是连接成功的,并且又正常的通信.
![image](https://user-images.githubusercontent.com/16284566/164414830-c1d091af-c901-44a8-9813-3687144230e8.png)
是还需要配置什么嘛?还是又什么地方配置错误了?

**Comment by CQ-Wangrz** [comment]
看了下源码已经可以了,
要使用 builder.Host.UseAgileConfig();
我原来使用的, builder.Configuration.AddAgileConfig();

**Comment by kklldog** [comment]
是的 新版本推荐使用 UseAgileConfig 方法注册相关服务。
