### ISSUE TITLE
trace log 好像没有办法关闭？

### ISSUE THREAD

**Issue by lamjack** [dotnetcore/AgileConfig#88]
好像默认就已经设置了 console logger，看了下代码好像也没有关闭或者设置日志级别的途径？

**Comment by lamjack** [comment]
明白了，我替换了系统那个，我用的Serilog，所以...

**Comment by kklldog** [comment]
那你 serilog 不注册成系统的 logger provider 吗

**Comment by kklldog** [comment]
如果你是调试模式的化要看一下 dev 那个配置文件是不是也改了 level ，还是你是怎么注册 agileconfig 的，是使用 use 方法还是怎么，贴一下，我试了下试可以起作用的。

**Comment by lamjack** [comment]
use 方法。

<img width="759" alt="Screen Shot 2022-05-19 at 18 28 43" src="https://user-images.githubusercontent.com/8164447/169273052-b5beded0-a809-4fea-9f73-210c95c1169f.png">

<img width="834" alt="Screen Shot 2022-05-19 at 18 29 13" src="https://user-images.githubusercontent.com/8164447/169273146-bb1b475e-447e-494f-8109-5268466bb77d.png">

**Comment by kklldog** [comment]
```
host.UseAgileConfig();
```
or
```
servicesCollection.AddAgileConfig();
```
这样注入

**Comment by lamjack** [comment]
还是会出 trace log..

<img width="612" alt="Screen Shot 2022-05-20 at 16 03 23" src="https://user-images.githubusercontent.com/8164447/169482882-bd2ef611-4a71-47ff-94c1-2fd135439109.png">

**Comment by kklldog** [comment]
你那行 clearproviders 是不是有问题

**Comment by lamjack** [comment]
那行我去掉了，那个是为了 debug 是不是每次 agile client 都会 new 一个新的 console logger，我再试试吧。

**Comment by kklldog** [comment]
启动的时候new一个，但是调用add方法的时候会替换掉：
https://github.com/kklldog/AgileConfig_Client/blob/master/AgileConfig.Client/ServiceCollectionExtension.cs#L11

**Comment by lamjack** [comment]
@kklldog 还是同样的问题..只要用UseSerilog一定会输出trace，可否给一个联系方式，我远程一个remote desktop给你看下。

**Comment by kklldog** [comment]
> @kklldog 还是同样的问题..只要用UseSerilog一定会输出trace，可否给一个联系方式，我远程一个remote desktop给你看下。
最多只会输出开头3行日志，你可以试试我那个sample里的 net6项目，把 useserilog 的注释去了。
17014842 # qq .com

**Comment by kklldog** [comment]
> @kklldog 还是同样的问题..只要用UseSerilog一定会输出trace，可否给一个联系方式，我远程一个remote desktop给你看下。

最多只会输出开头3行日志，你可以试试我那个sample里的 net6项目，把 useserilog 的注释去了。
17014842 # qq .com
