### ISSUE TITLE
大佬 想问一下怎么配置下面这个复杂数据结构？

### ISSUE THREAD

**Issue by imtudou** [dotnetcore/AgileConfig#90]
![image](https://user-images.githubusercontent.com/37775915/177066268-3cf31286-a128-4647-bdcf-4a75bb86517f.png)
![image](https://user-images.githubusercontent.com/37775915/177067117-585b4e4b-b452-4057-aeef-73d954669946.png)

**Comment by kklldog** [comment]
这种就直接用 ” 编辑json“ 功能好了

**Comment by imtudou** [comment]
> 这种就直接用 ” 编辑json“ 功能好了

那可能是我这边用的版本比较老吧  刚刚对比了下才发现你这边已经更新了版本
![image](https://user-images.githubusercontent.com/37775915/178394166-a2e100f5-ef2c-497a-9bdc-96ca669c64e4.png)

**Comment by kklldog** [comment]
> > 这种就直接用 ” 编辑json“ 功能好了
> 
> 那可能是我这边用的版本比较老吧 刚刚对比了下才发现你这边已经更新了版本 ![image](https://user-images.githubusercontent.com/37775915/178394166-a2e100f5-ef2c-497a-9bdc-96ca669c64e4.png)

嗯， 你这个看起来比较老的版本了，更新的话可能会确表。建议全新建一个库直接生成最新的表，然后旧的系统导出json，然后导入到新的系统。

**Comment by imtudou** [comment]
> > > 这种就直接用 ” 编辑json“ 功能好了
> > 
> > 
> > 那可能是我这边用的版本比较老吧 刚刚对比了下才发现你这边已经更新了版本 ![image](https://user-images.githubusercontent.com/37775915/178394166-a2e100f5-ef2c-497a-9bdc-96ca669c64e4.png)
> 
> 嗯， 你这个看起来比较老的版本了，更新的话可能会缺表。建议全新建一个库直接生成最新的表，然后旧的系统导出json，然后导入到新的系统。

但是目前来看 不能更新到最新的 因为我们公司目前的项目都是3.1 的  可能要改造一下了

**Comment by kklldog** [comment]
> > > > 这种就直接用 ” 编辑json“ 功能好了
> > > 
> > > 
> > > 那可能是我这边用的版本比较老吧 刚刚对比了下才发现你这边已经更新了版本 ![image](https://user-images.githubusercontent.com/37775915/178394166-a2e100f5-ef2c-497a-9bdc-96ca669c64e4.png)
> > 
> > 
> > 嗯， 你这个看起来比较老的版本了，更新的话可能会缺表。建议全新建一个库直接生成最新的表，然后旧的系统导出json，然后导入到新的系统。
> 
> 但是目前来看 不能更新到最新的 因为我们公司目前的项目都是3.1 的 可能要改造一下了

没关系的，你使用的只是用client，client是支持3.1的
