### ISSUE TITLE
修改文档中的环境变量写法

### ISSUE THREAD

**Issue by kami-poi** [dotnetcore/AgileConfig#95]
文档中环境变量是这种写法的 
**db:conn**
这种写法使用了冒号，但是冒号不是所有环境都支持的，详见[ASP.NET Core 中的配置](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#non-prefixed-environment-variables) 
因此建议替换冒号为任何环境都支持的双下划线 
**db__conn**这样，asp.net 环境变量配置提供程序会自动转化为冒号的形式。

**Comment by kklldog** [comment]
不错的建议，就是__辨识度好低。docker docker-compose k8s 下你测过吗？

**Comment by kami-poi** [comment]
我就是在k8s上部署时遇到了这个问题，所以过来建议的。 
已经在k8s上测试过，可以正常运行。
其他环境未做测试。不过下划线本来就是环境变量里面常见元素，各种环境应该都是支持的。

**Comment by kklldog** [comment]
docker 下我试过了，没问题，已合并了。

**Comment by lihc520** [comment]
> 

大佬能否给个在k8s上面部署的yml，我部署了一直有问题
