### ISSUE TITLE
AgileConfig 未能根据ASPNETCORE_ENVIRONMENT不同，读取不同的文件

### ISSUE THREAD

**Issue by sampsonye** [dotnetcore/AgileConfig#99]
需求：传入不同的ASPNETCORE_ENVIRONMENT，读取不同的的appsetting.json

**Comment by sampsonye** [comment]
目前暂时通过options代码手动配置解决
```csharp
builder.Host.UseAgileConfig(b => {
    return ConfigClientOptions.FromConfiguration(builder.Configuration);
});
```

**Comment by kklldog** [comment]
.UseAgileConfig(new ConfigClient($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")}.json"), e => Console.WriteLine($"configs {e.Action}"))
这样好了
